"use client";

import { useState } from "react";

import "./globals.css";
import type { Metadata } from "next";
import { ReduxProvider } from "@/store/provider";
import { MapProvider } from "react-map-gl";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  hud,
}: {
  children: React.ReactNode;
  hud: React.ReactNode;
}) {
  const [value, setValue] = useState("option 2");
  const [slider, setSlider] = useState([0]);
  const [play, setPlay] = useState(false);

  const onChange = (e: string) => {
    setValue(e === value ? "" : e);
  };

  const onSlideChange = (event: number[]) => {
    setSlider(event);
  };
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={"relative text-foreground bg-background font-pt"}
      >
        <ReduxProvider>
          <MapProvider>
            <div className="h-screen">{children}</div>
            {hud}
          </MapProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
