import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  hud,
}: {
  children: React.ReactNode;
  hud: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={"relative text-foreground bg-background font-pt"}>
        <div className="min-h-screen ">{children}</div>
        <div className="min-h-screen absolute inset-0">{hud}</div>
      </body>
    </html>
  );
}
