
export const TSP = {
  NEAREST_NEIGHBOR: "NEAREST_NEIGHBOR",
  NEAREST_INSERTION: "NEAREST_INSERTION",
  RANDOM_INSERTION: "RANDOM_INSERTION",
  FURTHEST_INSERTION: "FURTHEST_INSERTION",
  CHEAPEST_INSERTION: "CHEAPEST_INSERTION",
  CONVEX_HULL: "CONVEX_HULL",
  TWO_OPT_INVERSION: "TWO_OPT_INVERSION",
  DYNAMIC_PROGRAMMING: "DYNAMIC_PROGRAMMING",
  DEPTH_FIRST_SEARCH: "DEPTH_FIRST_SEARCH",
} as const;

